### ISSUE TITLE
Card expired

### ISSUE THREAD

**Issue by lgiordani** [skiller-whale/solid-principles-in-python#7]
I recommend updating the dates in https://github.com/skiller-whale/solid-principles-in-python/blob/main/open_closed/payments/main.py#L15 and https://github.com/skiller-whale/solid-principles-in-python/blob/main/open_closed/payments_no_conditionals/main.py#L15 as the output doesn't match what the slides say ("7. Open for Extension" -> Exercise)

**Comment by traikodinev** [comment]
https://github.com/skiller-whale/solid-principles-in-python/pull/8

**Comment by lgiordani** [comment]
Thanks!

**Comment by davidmillican** [comment]
Thanks @lgiordani ! 🙌
